<?php
//document types
define("DOC_NAME", array("PAN CARD", "ADDHAAR CARD", "RATION CARD", "PASSPORT", "BIRTH CERTIFICATE", "DRIVING LISCENECE", "VEHICLE REGISTRATION CERTIFICATE", "VOTAR CARD", "PASSBOOK", "MARKSHEETS", "OTHERS"));
