<?php

//expanse category
DEFINE("EXPANSE_CATEGORIES", array("RECHARGE & BILLINGS", "TRANSPORTATION", "MARKETING & ADVERTISING", "OFFICE EXPANSE", "DOMAIN, HOSTING & IT SERVICES", "SALARY & STIPENDS", "EVENT & FUNCTIONS", "OTHERS"));
